## UW-Madison COVID data, Fall 2021

Plot of data from the [UW-Madison COVID
dashboard](https://covidresponse.wisc.edu/dashboard/) from Fall, 2021,
manually entered in [`uw_covid_2021.csv`](uw_covid_2021.csv).

Here, just calculating and plotting the test positivity;
the curves are 7-day running averages.
The shaded regions are pointwise 95% confidence intervals on the 7-day
running averages.
The source is in [`README.Rmd`](README.Rmd).

```{r options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,
                      fig.path="", fig.width=11, fig.height=14)
```


```{r load_data_and_calculate}
x <- read.csv("uw_covid_2021.csv")

tot <- rowSums(x[,2:3])
pos <- rowSums(x[,4:5])
x <- cbind(x, Total=tot, Positive=pos)
x <- cbind(x,
           percent_employees = x[,4]/x[,2]*100,
           percent_students = x[,5]/x[,3]*100,
           percent_overall = x[,7]/x[,6]*100)

x <- cbind(x,
           week_employees=NA,
           week_students=NA,
           week_overall=NA,
           lo_employees=NA,
           lo_students=NA,
           lo_overall=NA,
           hi_employees=NA,
           hi_students=NA,
           hi_overall=NA)
for(i in 1:nrow(x)) {
    val <- i+(-6:0)
    val <- val[val >= 1]
    pos <- colSums(x[val,c(4,5,7)])
    tot <- colSums(x[val,c(2,3,6)])
    x[i,ncol(x)+(-8:-6)] <- pos/tot*100
    ci <- lapply(1:3, function(i) {if(!is.na(tot[i]) && tot[i] > 0) return(binom.test(pos[i], tot[i])$conf.int*100) else return(c(NA,NA))})
    x[i,ncol(x)+(-5:-3)] <- sapply(ci, "[", 1)
    x[i,ncol(x)+(-2:0)] <- sapply(ci, "[", 2)
}
```

```{r ci_envelope}
ci_envelope <-
    function(x, lo, hi, ...)
{

}
```


```{r bar_plots, dev="svg"}
light_color <- c(green="#A8DC93", blue="#B3C7E5", red="#F78FA7")
dark_color <- c(green="#0D8308", blue="#0855B3", red="#C5050C")

cols <- c(8,9,10)
ave_cols <- c(11,12,13)
mx <- max(x[,c(cols, ave_cols)], na.rm=TRUE)
lab <- c("Employees", "Students", "Overall")

test_date <- as.Date(x[,1])
monfri <- (lubridate::wday(test_date) %in% c(2, 6))

par(mfrow=c(3,1), cex=1.3)
for(i in 3:1) {
    z <- barplot(x[, cols[i]], col=light_color[i], main=lab[i],
                 las=1, ylim=c(0, mx), space=0.02,
                 ylab="Percent Positive", xaxs="i")
    abline(h=pretty(c(0,mx)), lty=2, col="gray60")

    u <- par("usr")
    v <- z[,1]
    vv <- v + diff(v[1:2])*0.3
    segments(v[monfri], u[3], v[monfri], u[3]-diff(u[3:4])*0.04, xpd=TRUE)
    text(vv[monfri], u[3] - diff(u[3:4])*0.08, x[monfri,1], adj=c(1, 0.5), srt=45, xpd=TRUE)

    lines(v, x[,ave_cols[i]], col=dark_color[i], lwd=2)

    polygon(c(v,rev(v)), c(x[,ave_cols[i]+3], rev(x[,ave_cols[i]+6])),
            col=paste0(light_color[i], "40"), border=NA, xpd=TRUE)
}
```
